name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    name: MacOS CPU-only
    runs-on: macos-10.5

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install boost openssl protobuf

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCOMPILE_CPU=on \
          -DCOMPILE_CUDA=off \
          -DCOMPILE_EXAMPLES=on \
          -DCOMPILE_SERVER=on \
          -DCOMPILE_TESTS=on \
          -DUSE_FBGEMM=on \
          -DUSE_SENTENCEPIECE=on

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests
      working-directory: build
      run: make test

    - name: Print versions
      working-directory: build
      run: |
        ./marian --version
        ./marian-decoder --version
        ./marian-scorer --version
        ./spm_encode --version
        ls -hlv $(find . -maxdepth 1 -type f -perm +ugo+x \( -name "marian*" -o -name "spm*" \))

    - name: Install PyMarian
      working-directory: build
      run: |
        python3 -m venv .venv && source .venv/bin/activate
        python3 -m pip install -U setuptools wheel
        python3 -m pip install pybind11 sentencepiece scikit-build
        cd ../src/python
        python3 setup.py install -j2
        cd ../../
        python3 -c "from pymarian import Translator"
